version: "3.5"

services:
    fk-reposilite:
        image: dzikoysk/reposilite:3.5.10
        ports:
            - "9333:8080"
        environment:
            - JAVA_OPTS=-Xmx64M
            - REPOSILITE_OPTS=--port 8080 --token admin:secret
        volumes:
            - reposilite-data:/app/data
        restart: unless-stopped
        stdin_open: true
        tty: true
volumes:
    reposilite-data: {}