stages:
    - deploy

fk_backend1:
    stage: deploy
    before_script:
        - docker info
    script:
        - cd $CI_PROJECT_DIR && cp ./_services/fk_backend1/src/main/resources/templates/application-prod.properties ./_services/fk_backend1/src/main/resources/application.properties
        - ./gradlew clean build -p _services/fk_backend1 -x test
        - docker-compose -f _services/fk_backend1/docker-compose-backend1.yml up -d --build
        - echo "fk_backend1 pipeline finished"
    tags:
        - shell