version: "3.5"

services:
  fk-backend1:
    container_name: fk-backend1
    environment:
        DATABASE1_HOSTNAME: fk-database1
        DATABASE1_PORT: 3306
        COGNITO_USERPOOLID: test123
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 9050:8080
    networks:
      - fk-framework

networks:
    fk-framework:
        external: true