version: "3.5"

services:
  fk-backend2:
    container_name: fk-backend2
    environment:
      DATABASE1_HOSTNAME: fk-database1
      DATABASE1_PORT: 3306
      DATABASE2_HOSTNAME: fk-database2
      DATABASE2_PORT: 5432
      COGNITO_USERPOOLID: test123
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 9051:8080
    networks:
      - fk-framework

networks:
    fk-framework:
        external: true